// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(OpticsDbConnectionStringContext))]
    partial class OpticsDbConnectionStringContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Server.MigrationHistory", b =>
                {
                    b.Property<string>("MigrationId")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ContextKey")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<byte[]>("Model")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ProductVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("MigrationId", "ContextKey")
                        .HasName("PK_dbo.__MigrationHistory");

                    b.ToTable("__MigrationHistory", (string)null);
                });

            modelBuilder.Entity("Server.Optic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Coating")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrameMaterial")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Frame_Material");

                    b.Property<bool>("InInstallments")
                        .HasColumnType("bit")
                        .HasColumnName("In_Installments");

                    b.Property<string>("LeftLens")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Left_Lens");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("RightLens")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Right_Lens");

                    b.HasKey("Id")
                        .HasName("PK_dbo.Optics");

                    b.ToTable("Optics");
                });
#pragma warning restore 612, 618
        }
    }
}
